detector:
  name: B000035A
  position: 5.0
holder:
  geometry:
    bottom_cyl:
      inner:
        height_in_mm: 0
        radius_in_mm: 0
      outer:
        height_in_mm: 0
        radius_in_mm: 0
    cylinder:
      inner:
        height_in_mm: 62.5
        radius_in_mm: 37.8
      outer:
        height_in_mm: 65.5
        radius_in_mm: 39.3
    edge:
      height_in_mm: 0
      radius_in_mm: 0
    rings:
      height_in_mm: 8.6
      position_bottom_ring_in_mm: 0
      position_top_ring_in_mm: 14.7
      radius_in_mm: 40.8
  position: 4.0
wrap:
  geometry:
    inner:
      height_in_mm: 49.0
      radius_in_mm: 37.0
    outer:
      height_in_mm: 50.0
      radius_in_mm: 37.5
  position: 4.0
