detector:
  name: B00000B
  position: 5.0
holder:
  geometry:
    bottom_cyl:
      inner:
        height_in_mm: 0
        radius_in_mm: 0
      outer:
        height_in_mm: 0
        radius_in_mm: 0
    cylinder:
      inner:
        height_in_mm: 62.5
        radius_in_mm: 41.0
      outer:
        height_in_mm: 65.5
        radius_in_mm: 39.5
    edge:
      height_in_mm: 0
      radius_in_mm: 0
    rings:
      height_in_mm: 8.6
      position_bottom_ring_in_mm: 0
      position_top_ring_in_mm: 14.7
      radius_in_mm: 41.5
  position: 3.5
wrap:
  geometry:
    inner:
      height_in_mm: 49.0
      radius_in_mm: 37.2
    outer:
      height_in_mm: 50.0
      radius_in_mm: 37.7
  position: 3.5
