detector:
  name: V00048B
  position: 7.0
holder:
  geometry:
    bottom_cyl:
      inner:
        height_in_mm: 15.7
        radius_in_mm: 8.0
      outer:
        height_in_mm: 25.4
        radius_in_mm: 13.0
    cylinder:
      inner:
        height_in_mm: 105.0
        radius_in_mm: 37.5
      outer:
        height_in_mm: 108.1
        radius_in_mm: 38.3
    edge:
      height_in_mm: 1.3
      radius_in_mm: 40.5
    rings:
      height_in_mm: 8.6
      position_bottom_ring_in_mm: 64.4
      position_top_ring_in_mm: 14.0
      radius_in_mm: 40.5
  position: 6.0
wrap:
  geometry:
    inner:
      height_in_mm: 92.9
      radius_in_mm: 36.3
    outer:
      height_in_mm: 94.3
      radius_in_mm: 36.8
  position: 4.5
