detector:
  name: V03421A
  position: 19.0
holder:
  geometry:
    bottom_cyl:
      inner:
        height_in_mm: 15.9
        radius_in_mm: 8.0
      outer:
        height_in_mm: 25.4
        radius_in_mm: 13.0
    cylinder:
      inner:
        height_in_mm: 105.0
        radius_in_mm: 44.5
      outer:
        height_in_mm: 108.1
        radius_in_mm: 45.3
    edge:
      height_in_mm: 1.3
      radius_in_mm: 47.5
    rings:
      height_in_mm: 8.6
      position_bottom_ring_in_mm: 64.4
      position_top_ring_in_mm: 40.0
      radius_in_mm: 47.5
  position: 18.0
wrap:
  geometry:
    inner:
      height_in_mm: 99.0
      radius_in_mm: 43.5
    outer:
      height_in_mm: 100.0
      radius_in_mm: 44.2
  position: 18.0
