detector:
  name: V03422A
  position: 7.0
holder:
  geometry:
    bottom_cyl:
      inner:
        height_in_mm: 15.9
        radius_in_mm: 8.0
      outer:
        height_in_mm: 25.4
        radius_in_mm: 13.0
    cylinder:
      inner:
        height_in_mm: 118.0
        radius_in_mm: 45.0
      outer:
        height_in_mm: 121.1
        radius_in_mm: 45.8
    edge:
      height_in_mm: 1.3
      radius_in_mm: 48.0
    rings:
      height_in_mm: 8.6
      position_bottom_ring_in_mm: 77.4
      position_top_ring_in_mm: 40.0
      radius_in_mm: 48.0
  position: 5.5
wrap:
  geometry:
    inner:
      height_in_mm: 118.5
      radius_in_mm: 44.0
    outer:
      height_in_mm: 119.5
      radius_in_mm: 44.7
  position: 4.5
