detector:
  name: V04199A
  position: 7.0
holder:
  geometry:
    bottom_cyl:
      inner:
        height_in_mm: 15.9
        radius_in_mm: 8.0
      outer:
        height_in_mm: 25.4
        radius_in_mm: 13.0
    cylinder:
      inner:
        height_in_mm: 112.0
        radius_in_mm: 44.0
      outer:
        height_in_mm: 115.1
        radius_in_mm: 44.8
    edge:
      height_in_mm: 1.3
      radius_in_mm: 47.0
    rings:
      height_in_mm: 8.6
      position_bottom_ring_in_mm: 71.4
      position_top_ring_in_mm: 14.0
      radius_in_mm: 47.0
  position: 6.0
wrap:
  geometry:
    inner:
      height_in_mm: 105.5
      radius_in_mm: 43.0
    outer:
      height_in_mm: 106.5
      radius_in_mm: 43.6
  position: 6.0
