detector:
  name: V04549B
  position: 7.0
holder:
  geometry:
    bottom_cyl:
      inner:
        height_in_mm: 15.9
        radius_in_mm: 8.0
      outer:
        height_in_mm: 25.4
        radius_in_mm: 13.0
    cylinder:
      inner:
        height_in_mm: 79.0
        radius_in_mm: 39.0
      outer:
        height_in_mm: 82.1
        radius_in_mm: 39.8
    edge:
      height_in_mm: 1.3
      radius_in_mm: 42.0
    rings:
      height_in_mm: 8.6
      position_bottom_ring_in_mm: 38.4
      position_top_ring_in_mm: 14.0
      radius_in_mm: 42.0
  position: 6.0
wrap:
  geometry:
    inner:
      height_in_mm: 79.5
      radius_in_mm: 38.0
    outer:
      height_in_mm: 80.5
      radius_in_mm: 38.6
  position: 4.5
