detector:
  name: V07298B
  position: 8.0
holder:
  geometry:
    bottom_cyl:
      inner:
        height_in_mm: 19.5
        radius_in_mm: 8.0
      outer:
        height_in_mm: 29.0
        radius_in_mm: 13.0
    cylinder:
      inner:
        height_in_mm: 88.9
        radius_in_mm: 41.5
      outer:
        height_in_mm: 91.5
        radius_in_mm: 42.3
    edge:
      height_in_mm: 1.3
      radius_in_mm: 44.5
    rings:
      height_in_mm: 8.6
      position_bottom_ring_in_mm: 51.4
      position_top_ring_in_mm: 14.0
      radius_in_mm: 44.5
  position: 7.0
wrap:
  geometry:
    inner:
      height_in_mm: 81.0
      radius_in_mm: 40.5
    outer:
      height_in_mm: 82.0
      radius_in_mm: 41.2
  position: 7.0
