detector:
  name: V07646A
  position: 6.5
holder:
  geometry:
    bottom_cyl:
      inner:
        height_in_mm: 15.9
        radius_in_mm: 8.0
      outer:
        height_in_mm: 25.4
        radius_in_mm: 13.0
    cylinder:
      inner:
        height_in_mm: 105.0
        radius_in_mm: 42.5
      outer:
        height_in_mm: 108.1
        radius_in_mm: 43.3
    edge:
      height_in_mm: 1.3
      radius_in_mm: 45.5
    rings:
      height_in_mm: 8.6
      position_bottom_ring_in_mm: 49.5
      position_top_ring_in_mm: 14.0
      radius_in_mm: 45.5
  position: 5.5
wrap:
  geometry:
    inner:
      height_in_mm: 99.0
      radius_in_mm: 41.5
    outer:
      height_in_mm: 100.0
      radius_in_mm: 42.2
  position: 5.5
