detector:
  name: V09372A
  position: 7.0
holder:
  geometry:
    bottom_cyl:
      inner:
        height_in_mm: 15.9
        radius_in_mm: 8.0
      outer:
        height_in_mm: 25.4
        radius_in_mm: 13.0
    cylinder:
      inner:
        height_in_mm: 130.0
        radius_in_mm: 47.5
      outer:
        height_in_mm: 133.1
        radius_in_mm: 48.3
    edge:
      height_in_mm: 1.3
      radius_in_mm: 50.5
    rings:
      height_in_mm: 8.6
      position_bottom_ring_in_mm: 89.4
      position_top_ring_in_mm: 14.0
      radius_in_mm: 50.5
  position: 6.0
wrap:
  geometry:
    inner:
      height_in_mm: 124.0
      radius_in_mm: 46.4
    outer:
      height_in_mm: 125.0
      radius_in_mm: 47.1
  position: 6.0
