detector:
  name: V09724A
  position: 7.0
holder:
  geometry:
    bottom_cyl:
      inner:
        height_in_mm: 15.9
        radius_in_mm: 8.0
      outer:
        height_in_mm: 25.4
        radius_in_mm: 13.0
    cylinder:
      inner:
        height_in_mm: 105.0
        radius_in_mm: 46.5
      outer:
        height_in_mm: 108.1
        radius_in_mm: 47.3
    edge:
      height_in_mm: 1.3
      radius_in_mm: 49.5
    rings:
      height_in_mm: 8.6
      position_bottom_ring_in_mm: 60.0
      position_top_ring_in_mm: 14.0
      radius_in_mm: 49.5
  position: 6.0
wrap:
  geometry:
    inner:
      height_in_mm: 102.0
      radius_in_mm: 45.5
    outer:
      height_in_mm: 103.0
      radius_in_mm: 46.2
  position: 6.0
