detector:
  name: V10447B
  position: 7.0
holder:
  geometry:
    bottom_cyl:
      inner:
        height_in_mm: 0.0
        radius_in_mm: 6.0
      outer:
        height_in_mm: 0.0
        radius_in_mm: 13.0
    cylinder:
      inner:
        height_in_mm: 12.0
        radius_in_mm: 6.0
      outer:
        height_in_mm: 12.0
        radius_in_mm: 6.0
    edge:
      height_in_mm: 12.0
      radius_in_mm: 6.0
    rings:
      height_in_mm: 12.0
      position_bottom_ring_in_mm: 12.0
      position_top_ring_in_mm: 12.0
      radius_in_mm: 6.0
  position: 6.0
wrap:
  geometry:
    inner:
      height_in_mm: 12.0
      radius_in_mm: 6.0
    outer:
      height_in_mm: 12.0
      radius_in_mm: 6.0
  position: 6.0
