detector:
  name: V14673A
  position: 6.0
holder:
  geometry:
    bottom_cyl:
      inner:
        height_in_mm: 15.9
        radius_in_mm: 8.0
      outer:
        height_in_mm: 25.4
        radius_in_mm: 13.0
    cylinder:
      inner:
        height_in_mm: 117.0
        radius_in_mm: 47.2
      outer:
        height_in_mm: 120.1
        radius_in_mm: 48.0
    edge:
      height_in_mm: 1.3
      radius_in_mm: 50.2
    rings:
      height_in_mm: 8.6
      position_bottom_ring_in_mm: 76.4
      position_top_ring_in_mm: 14.0
      radius_in_mm: 50.2
  position: 5.0
wrap:
  geometry:
    inner:
      height_in_mm: 112.0
      radius_in_mm: 46.0
    outer:
      height_in_mm: 113.0
      radius_in_mm: 46.7
  position: 5.0
